name: Relase distribution

on:
  push:
    branches:
    - '**'

jobs:
  build_and_push:
    runs-on: ubuntu-18.04

    steps:
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Extract
      id: extract
      run: |
        echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"

    - name: Release
      uses: satackey/release-js-action@release-master
      with:
        release-branch: release-${{ steps.extract.outputs.branch }}
